// 1.18: Player.hideEntity, which makes floating numbers per-viewer.
dependencies {
    compileOnly project(':bukkit')
    compileOnly project(':compat-1.8')
    compileOnly project(':compat-1.9')
    compileOnly project(':compat-1.14')
    compileOnly "org.spigotmc:spigot-api:${spigot_api_1_18}"
}
